### PR TITLE
MoveMigrationsFolderInDataBaseFolder

### PR DESCRIPTION
**Pull request by denis-kriv**
Moved migrations folder in database folder in all services

### CODE REVIEW

**Review by mekk1t — APPROVED** [review]
Yeah, all migrations are moved to the "Database/Migrations/"

Question: EF Core will still be able to find and apply them? And if we add a new migration, where will it be created?

**Comment by DarkFelas** [comment]
> Yeah, all migrations are moved to the "Database/Migrations/"
> 
> Question: EF Core will still be able to find and apply them? And if we add a new migration, where will it be created?

https://docs.microsoft.com/ru-ru/ef/core/managing-schemas/migrations/managing?tabs=vs#namespaces

**Review by ifelseelif — APPROVED** [review]

**Review by MihailKulikov — DISMISSED** [review]
Migrations of CompanyService are not moved to the "Database/Migrations/"

**Review by Inzilbeth — APPROVED** [review]

**Review by lalagvana — APPROVED** [review]

**Review by djino97 — APPROVED** [review]

**Review by KostinP — APPROVED** [review]

**Review by DarkFelas — CHANGES_REQUESTED** [review]
CompanyService

**Review by DarkFelas — APPROVED** [review]

**Pull request merged**
