### PR TITLE
CompanyService_DbContext

### PR DESCRIPTION
**Pull request by MihailKulikov**
CompanyService project is added to the solution.
DbContext is defined and the database is created locally using PM console.

### CODE REVIEW

**Comment by KostinP** [comment]
Please rename the pull request.

**Comment by KostinP** [comment]
Please add an appropriate blank test project.

**Comment by DarkFelas** [comment]
> Please add an appropriate blank test project.

No need, there is already test project in solution

**Comment by lalagvana** [comment]
The title of the pull-request must not have "feature/".

**Review by lalagvana — APPROVED** [review]

**Review by djino97 — APPROVED** [review]

**Review by denis-kriv — APPROVED** [review]

**Review by Inzilbeth — APPROVED** [review]

**Review by mekk1t — APPROVED** [review]

**Pull request merged**
